BaseStackName: 'com-example-api'

Stages:
  Source: true
  Build: true
  Install: true
  UT: true
  ST: true
  UAT: true
  Production: true

Approvals:
  ST: true
  UAT: true
  Production: true

Notifications:
  PipelineNotification:
    DisplayName: 'Pipeline'
    Subscription:
      - Endpoint: 'maillist@example.com'
        Protocol: email
    States:
      STARTED: true
      SUCCEEDED: true
      RESUMED: true
      FAILED: true
      CANCELED: true
      SUPERSEDED: true
  StagingNotification:
    DisplayName: 'Staging'
    Subscription:
      - Endpoint: 'maillist@example.com'
        Protocol: email
    Stages:
      Source: true
      Build: true
      Install: true
      UT: true
      ST: true
      UAT: true
      Production: true
    States:
      STARTED: true
      SUCCEEDED: true
      RESUMED: true
      FAILED: true
      CANCELED: true
  STApproval:
    DisplayName: 'ST'
    Subscription:
      - Endpoint: 'maillist@example.com'
        Protocol: email
  UATApproval:
    DisplayName: 'UAT'
    Subscription:
      - Endpoint: 'maillist@example.com'
        Protocol: email
  ProductionApproval:
    DisplayName: 'PRODUCTION'
    Subscription:
      - Endpoint: 'maillist@example.com'
        Protocol: email

Microservices:
  helloworld1:
    Sources:
      MainSrc:
        ActionTypeId:
          Category: Source
          Owner: ThirdParty
          Version: 1
          Provider: GitHub
        Configuration:
          Owner: RazzM13
          Repo: nodejs-scaffold-aws-apigateway-microservice
          Branch: master
          OAuthToken: ******
          PollForSourceChanges: true
        RunOrder: 1
    BuildSource: MainSrc
    TestSource: MainSrc
