{{#each Microservices}}
- InputArtifacts:
    - Name: {{@key}}-{{BuildSource}}
  Name: {{@key}}-Build
  ActionTypeId:
    Category: Build
    Owner: AWS
    Version: '1'
    Provider: CodeBuild
  OutputArtifacts:
    - Name: {{@key}}-Build
  Configuration:
    ProjectName:
      Ref: CodeBuildBuildProject
  RunOrder: 1
{{/each}}
